<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\EventInterface;

/**
 * Cartography Controller
 *
 */
class CartographyController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->Auth->allow();
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


    public function index()
    {

    }

    public function interactiveMap()
    {




    }


    public function getDataByLocalidadIdAll()
    {

        $this->autoRender = false;

        $localidades = null;

        //comprobacion de definicion de variable
        if(isset($_POST['localidades']))
        {
            $localidades = $_POST['localidades'];
        }


        if($this->request->is('ajax')) {

            //compruebo que el array no este vacio
            if(count($localidades) > 0)
            {
                //Recorro el arreglo de localidades
                $array_or = [];

                foreach ($localidades as $loc){

                    array_push($array_or, $loc['fid']);
                }

                //model localidades
                $localidades_model = $this->loadModel('Localidades');
                $localidades_data = $localidades_model->find('all',
                    []
                )->where(['id_loc_icon IN ' => $array_or])
                    ->toArray();

                return $this->json($localidades_data);
            }
        }

        return false;
    }


    public function getDataLocalidadById()
    {
        $id = $_POST['id'];

        //model localidades
        $localidades_model = $this->loadModel('Localidades');

        if($this->request->is('ajax')) {

            $localidades_data = $localidades_model->find('all', [])
                ->where(['id_loc_icon' => $id])->toArray();


            return $this->json($localidades_data);
        }


        return false;
    }

    public function getDataPOIById()
    {
        $id = $_POST['id'];
        $id_loc = $_POST['id_loc'];

        //model localidades
        $puntosdeinteres_model = $this->loadModel('PuntosInteres');

        if($this->request->is('ajax')) {

            $puntos_interes_data = $puntosdeinteres_model->find('all', [])
                ->where(['id_punto' => $id, 'localidad' => $id_loc])->toArray();


            return $this->json($puntos_interes_data);
        }


        return false;
    }


}
