<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\Event\EventInterface;

/**
 * Index Controller
 *
 */
class IndexController extends AppController
{

    public function beforeFilter(Event $event)
    {

        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow('index');

    }

    public function index()
    {

        //Traigo los datos del slider
        $slider_home_model = $this->loadModel('SliderHome');


        //Consulto por la cantidad, y si no hay, no agrego el panel
        $query = $slider_home_model->find();
        $query->select(['count' => $query->func()->count('*')])
            ->where(['is_show' => true]);

        $res_count_slider = $query->toArray();
        $slider_count = $res_count_slider[0]['count'];

        if($slider_count >= 3){
            $slider_home = $slider_home_model->find('all', [])
                ->where(['is_show' => true]);
            $this->set(compact('slider_home'));
        }

        $this->set(compact('slider_count'));

    }

}
