<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\EventInterface;

/**
 * Integrantes Controller
 *
 * @property \App\Model\Table\IntegrantesTable $Integrantes
 */
class IntegrantesController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->Auth->allow();
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        $integrantes = $this->paginate($this->Integrantes);


    }

}
