<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\EventInterface;

/**
 * Novedades Controller
 *
 * @property \App\Model\Table\NovedadesTable $Novedades
 */
class NovedadesController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->Auth->allow();
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        $novedades = $this->paginate($this->Novedades);


    }
}
