<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\EventInterface;

/**
 * Proyecto Controller
 *
 */
class ProyectoController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->Auth->allow();
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


    public function Index()
    {

        return $this->redirect(['controller' => 'Index', 'action' => 'index']);

    }
    public function Objetivos()
    {

    }

}
